### ISSUE TITLE
build 报错，提示文件不存在

### ISSUE THREAD

**Issue by bsqql123** [dmcBig/cordova-plugin-mixPush#1]
日志报错
cp: copyFileSync: could not write to dest file (code=ENOENT):/home/ice/WebstormProjects/MyCordova4/platforms/android/res/xml/config.xml

Parsing /home/ice/WebstormProjects/MyCordova4/platforms/android/res/xml/config.xml failed

**Comment by iceqing** [comment]
https://github.com/dmcBig/cordova-plugin-mixPush/pull/3

**Comment by dmcBig** [comment]
更新一下插件再试试

**Comment by dmcBig** [comment]
@iceqing 感谢你的提交方案已经合并你的分支，谢谢。
